### PR TITLE
ER図追加しました

### PR DESCRIPTION
**Pull request by ito-ryo-50a**
お世話になっております。
卒業制作のER図を提出いたします。

お手数ですがご確認いただけますでしょうか。
よろしくお願いいたします。

### ER図
drow.io：https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=%E5%8D%92%E6%A5%AD%E5%88%B6%E4%BD%9CER%E5%9B%B3.drawio#R7V3bcts4Ev0aPdrFu6TH2Ik3mUlqU85M7ey%2BuBgRllimCA0JxdZ8%2FYLiRRRbFCFRJGg1Uq6KCIMQDZzGQZ9ugCPzfvn2r8hdLb5RjwQjQ%2FPeRubHkWEYY83m%2FyUlm6xEn07Tknnke2mZviv44f9DskItK137Hon3KjJKA%2Bav9gtnNAzJjO2VuVFEX%2FerPdNg%2F1tX7pyAgh8zN4Cl%2F%2FE9tkhLJ7a2K%2F9M%2FPki%2F2Zdy36zdPPKWUG8cD36uldE3tgDDVn2iN9JtHRDEjL%2Bm29u9EKikf1pwVjyl34YGQ%2F85zmpfTundB4Qd%2BXHtzO65MWzmFd5eHaXfpD0c6mhu6wh%2FnXmp5F5H1HK0k%2FLt3sSJIOVD0P6TA81vy36IUraFbhhHD7HH5y3f8e%2FrbSI3Uf%2Fo7%2BNb8ysmV9usM46%2BJHM%2FBXhZV%2FCeUQ8nyT9kXYY2%2BSjwPtulXxk7s%2Bk6C5mbsQysJgaL%2BDDz1w%2F5H%2Bp%2BVHfXgeBu4r9bfW0ZOEH3ld3Q9csbyi%2Funv234j3mGIlqcth85U3llwmjSe9%2FiN7mOTXbuDPQ%2F55xp81%2Bca7iMT8Wb66MctqLNgyyD4u6S939xTbmuVrylxWuub2Q8rXvEPKlwGdvRAve6wM8qVfZ51LIkbeaodNL8DArZbQJWHRhlfJbjCdDJuZwd5YZlbwuoO%2FPsnKFmXo5zbhZnieF43vYMI%2FZEg5BTUGQM1xhDwmdna3oJH%2FT4KLIOuwMmq216%2F%2BMuCG8pm4XqXojm5nrO3o%2B0FwTwOaQCukIQHoSip5EV394UZzwrKCFfUzw7bv%2BA%2Fvmnvt1h7Z%2FFnv%2BbW%2Bu%2BY%2FSXX%2B19IwZhFHcdIG4WB6JQmg7hhdZY0G5DlvP8o6Pvn8kzLG54GB4u3IRABRmKFOFHNmZ5AzAeS%2B%2F14LOv7nMt8NHpPeCecBOdhZB3B0cGSL0awOc3Uaorzjn4MtpSx8zyN8Srp7XfiM%2FFi5s6TSK%2BfkviajFlAwDkOhNPbmiUOfNbYbj5NbcwM%2Bs4cu4xPBOvRigKfiOVtAzAIQi7Zc%2BOTvmPCJNyEXdTnZpXXvYo4t%2Fnxf0zudCizt64fl26h2hrIvClOh5vrAqa3YV4h9tWthX0c6%2BzoAcg%2By2bcyNr3Pcpea1mykbDuuZVvOsNrWw9Yi8kx4%2F81IvQc6ENK9FpKtQSM%2Bkp0oksVFslPpJDtVJNsVyU5wkqylAUjtfFlFtDKJtgaR6IjWghEIRbRXTbS6IZtprRPiF4pnTxh5q2bkr55nYXTi77UbMp9tCorl5s%2BZTNFrL%2FRaB0R89AqDGkWA%2F7MfM06jR9Z87zC8L4SZ4%2Bi4KQYvT5KxBRmru5C7pUR%2F8ZB7i3nDOrp0kR4Gt6AQ3yYMXjO2vYfBWwwYUvncgvL5Yjudb1pFqC8CiD4i1JdHDL6lgZK4xT3vzihFemzXuqzsfJEZpL073GK8kGrF%2BaxUwsE6JtGlVeJ%2BGGYQiEHHKLbScgfAKNIDmTaUV1Ezio1UFbWhKtpNis8VckodZvBxChQwFaf0zinyY3b2CQIoAkqpGa6rpxSof84iwr%2FSe3JZwSkeL2D%2BkihGEYAMPkaB0ukdpS9LN3rhpQ808JL9udoXRpYqMlaJjDk5D5zKC0XFyxODkjH7iIylVjPcyJgNZUzckTEbqY6ZC%2BrlnFc%2Blauw2HlwQbc8cJSI2YfD2cAn0sNijhIxD5gFQjqBIubz1kVQIubZmMHHKUrEHACnSA%2BMOVDDxM0pSFVMB6qYPzMFSrHK2ahBxypj6OkCIVMpmA0KpjAr6IZ2q5X%2B6Xo9flqxxFg5oH0Imqn1DFfQHEMHFLegOUbqgY6PeqDDXhhIlTTrAINvoaDczz7czwZGkS5pjpX7ecAsEBIKdD9Vpn8rxOBjFJhDoxild0aRLmiOT8i9QcAnNfLz1fMJTL1RSZntIIOOUCbQyc21TCVhNkiYNxNdjAe6O55kojzMPjTL1EqGq1lOoIeJW7OcIHUxJw0RzmEvAaSqlnWQwbckUD5mHz5mA6dIVy0n0MdErVpOkHqZE%2Bhlqt3kLTGDjlNyxUxxikxOka5bTmGKDWpOmdbozNfOKVMD4EBFwlohBh%2BjQOFSMUrvjCL%2FfJLpCQooAkKpGa6rJxQogKpQWDvIoGMUXYerEoCUeUTXq9rO3gcLL9PgIDSdgZ%2FvLsiDTLpodMHo7KiPKVSV7%2BlymbyX%2BTjnjq4vRngMOkfn3b7HTKm4fUQGU9MYbmRwClVc3JHBKVIZd3ogWSidw1Vg8DzE4FsgaUrF7cPnbuAU6ZFBXVMy7iHDwEcqugZdJhUcbIsahMSixNwBEIv08KCuQTEXObEg1XN1DQq6KkLYDjMIaQXqlopWeqcV%2BTFCXTtBDMXAKjUDdv2sAtXQJByRdFfOKrw3meITEbQg5BO14fLiEbIKijaVIUeAKh2qquuVp1DVAaomiFAlcJodCb0PUbQdqwwMpVGJkmcj%2Bfo2vZd4c3KhESr12aEuy8siErjM%2F7X%2FrUeG5XuyfK4FgKFXRiKm62hGspt2o9DUDtjQy7ZLeNDO5UYTCmSPW52Vl30kzPUDfJkYDaeMOftDdnPI9vvdrK3rard2HzkZmbUMNylD19V%2B7YOmgdAl1aFGxZd6fEJXaRlnQgafX6qrXL8%2BdM4mXpGfmKGrPduHLAMjrahd25dHDT5myUM3ilmkMov8zAxDQE5CxCsG1oS%2FfNj3Imj0hc%2FWTzEjq7jgFm5LZJ680FkRSzNsEBKLyvgbArEMIDfDUBu4oWFgZBaoiXoknkX%2Bivk0HKn8jFMRg49ULAFS6XwDNzgl2BwLzrFGd5EnA6rMf8YY31J3DDhHJ93eR0xpur3ECo2Bb%2BDWDbWD%2B6BpYFwiQVG32BQx7BWR3EhhHWDwrZDy71Ss0q3b3cAq8iOFptJzoV0gpBQT6rlk6fpB4W9zO%2BJT%2BdD5ZRhoQcgnSsYdAp%2FIjw%2BaSsWFdoGRTw4exLlKNrOs3Dh%2BpZGnqOUM4CCkFrV5ewjUMoAIoal2b0PDwMgtUAmN%2BfcqPjkDLAj5BIqnoT97Cd1kT61CUG2%2F1cXG1MZtC4qp6jiAblCFaOO2BZVZdRxAJ6gqdoNjQBXUeQF0%2BjgOQCDTosfjAKzKSLyX4wAsqLZ9CecRd0tQvpPheEaWo%2B2PlnhClt7Z2xl0C%2Bpkx4cNq7rRlhFqNgkPJr3HgjIX8vSe1DQQ6hsW1Ln8YlZXST5nwgaf0mFBnUxxSwfKeQO3yE%2FysaDkJXkOkSqcp3aBkFjyiaksfSrZ8zyw4KMT%2B4RUQUUnndGJ%2FBwfW0BDQkQndo3scP10ApP%2BfD64T%2BtolzaqtmmKwgUfoYwFcgW73qaZz6a5JmhpgtNrh1v%2BbOj%2Fp4e84lN0jwHn6Izb%2B5gpX7sXHdeu2cI1GB3Xhr42ch3Xxupu58JP%2Bew9tzh7b9hrIrkabh1k8K2RHOV09%2BJ0N%2FCKfA3XgU437iNdHaxutwPdbvVKxHaYQcgr6hUUQ%2BAV%2BWKuc0ICEgZWwfr%2BCQfmH6nY4JlgQUgn6pSyIdDJADZpOicIoRj4BOsZZc6Bd6RmB4Sn%2B1UUr5wMGny8kmfol1C0Wv8M%2FHjxxKmCrXfnzP%2BkNCBuqIAkEiir275i4wEW1FXVns1uUDVBhCoo0pb2bCpIXQhSho4IUgInq%2FWxYVMg5%2BIdbtjMt9%2F1tWFzLKC2JYOTh165z7mgcxq6waddaRqcTZ1k3dgf7RIUPj1yLPxBv7nhBsCAvPnsr%2FwW%2Fvm%2FSfmtnV19fCtV%2B5h72Rwg0eav8kXpruRyd9v2aiMOuawoHcVj%2FZefhs5yR762piZwlLt2ALBFYUvE3hTQz1PL7HNfOr5L3M%2BbcqpNdY5bgUO4esHtmRjM8a6dgPcL4jZfbTbCViCo2S1qx5XXpZuWcWuU%2F5lnYtipNGxoYhDmqHA3pWqZalf%2FFziVlE4zO4qw%2FskqN%2BjTvRv4h%2FQZLmxRAopp2aI45ny2edwOLw07sir9HczsIsmf3U7sVmU2tqrrQmGjKE4eyY3C6cgoTKOKce34kxVnIxTm2lDfPq1%2BNfE6v79joxMQp4e6%2FJJibAJbJXs2NnN69ioK2G21qUtZW9XN4ObXwEHVOyo3dGUOAvuCe%2BMguSu0IoG%2F0SQEtnt1ahLnur4A%2FrrgCuxicMsDkdhnX2Goiby2vlOs2dWJDJxwJYo%2Bp9oS2IvTOfoEMqn7RN8pE90QFui5VNa8ZtAkg7b64sWzhRfwCsfedZeJMSzQvje9UHiqFThMu1PQQrWweuacsMQNxMJqS52DViRkoWbaC6wPNMlTbXVJefZMCxan%2Fc%2B0AgnxfftCZ82270HDm0rGLQzOtJAVqk2JygqXg%2B7AgoqDd%2BEnkt2qA%2FCr%2BuIt4NdVYMV0qg9tN6ha4I4%2BRK3JUEKV73TJLB5ilx6svKpZfDoUV%2B99htjz9VtziF12%2FHAC4hDngnZcaUnQ0Ts9pD6u2plz%2FMGqNxjtwhn8MqKUlatH7mrxjXokqfF%2F

### CODE REVIEW

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントなります。

---

- ER図の変更履歴を残しながら、やり取りを行いたいため、コメント欄に作成したER図のスクリーンショットを掲載していただけますでしょうか。（Gyazo・マークダウン）

- リレーションを表す線が重なっている箇所があり、テーブル間関係がわかりにくい箇所があるので、各線が独立するよう修正をお願いします。

**Comment by ito-ryo-50a** [comment]
お世話になっております。
ご確認いただきありがとうございます。

ER図修正いたしましたので再提出いたします。
お手数ですが、ご確認いただけますでしょうか。

[ER図リンク](https://gyazo.com/e1ac2b78f789524377c8c67b8b3cd99b)

スクリーンショット 2024-04-18 11 45 51

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
以下、コメントになります。

---

### 全体
- created_atやupdate_atのカラムが記載されている箇所と記載されていない箇所が見受けられるので、省略するなら省略、記載するなら全テーブルに記載するなど、統一すると良さそうです。

- ER図のテーブル、カラムの説明を、**アプリを知らない人に説明するような形を想定**して記載していただいてもよろしいでしょうか？

```
例
- usersテーブル （ユーザー情報を持つテーブル）
  - name : 名前
  - email：メールアドレス
  -  etc...

```

お手数ですがよろしくお願いします。

**Comment by ito-ryo-50a** [comment]
お世話になっております。
ご確認いただきありがとうございます。

下記、ご確認いただけますでしょうか。

・`created_at` `update_at`のカラムを全てのテーブルに記載しました。

・ER図のテーブル、カラムの説明を追加いたしました。

オートコンプリート機能の実装を予定しているため、一部が下記のようなテーブル構成となっております。
`Ingredients`テーブル(オートコンプリート実装のために食材の名前を登録しているテーブル)
`RecipeIngredients`テーブル(使用する食材のレシピへの紐付けと分量を記録するテーブル)

ご確認のほど、よろしくお願いいたします。

```
◽️Users (ユーザー情報のテーブル)
・user_id：主キー
・email：メールアドレス
・crepted_password：ハッシュ化されたパスワード 
・salt : パスワードソルト
・nickname：ニックネーム

◽️Recipes (レシピ情報のテーブル)
・recipe_id：主キー
・user_id：ユーザーID・外部キー
・name：レシピ名
・cooking_time： 調理時間
・public_status： 公開ステータス
・created_at： 作成日時
・updated_at：更新日時

◽️Ingredients (食材のテーブル)
・ingredient_id：主キー
・name： 食材名
・icon_url：アイコン画像URL

◽️RecipeIngredients (レシピで使用する材料のテーブル)
・recipe_ingredient_id：主キー
・recipe_id：レシピID・外部キー
・ingredient_id：食材ID・外部キー
・quantity：分量

RecipeDetails (レシピの詳細情報・調理手順のテーブル)
detail_id : 主キー
recipe_id : レシピID・外部キー
step_number : 手順番号
description : 説明

◽️Comments (レシピにつけるコメントのテーブル)
・comment_id：主キー
・recipe_id：レシピID・外部キー
・user_id：ユーザーID・外部キー
・content：コメント内容

◽️Bookmarks (ユーザーがピン留め「ブックマーク」したレシピのテーブル)
・bookmark_id：主キー
・user_id：ユーザーID・外部キー
・recipe_id：レシピID・外部キー
・created_at：作成日時

◽️BookmarkFolders (ブックマークのフォルダ分けをするテーブル)
・folder_id：主キー
・user_id：ユーザーID・外部キー
・name：フォルダ名
・created_at：作成日時

◽️BookmarkFolderItems (ブックマークフォルダーのアイテムを登録するテーブル)
・item_id：主キー
・folder_id：フォルダID・外部キー
・bookmark_id：ブックマークID・外部キー

◽️RecipeHistories (レシピの閲覧履歴を管理するテーブル)
・history_id：主キー
・user_id：ユーザーID・外部キー
・recipe_id：レシピID・外部キー
・viewed_at：閲覧日時

```

[ER図リンク](https://gyazo.com/4d8d670e73070a544ef34a70613fe38b)

スクリーンショット 2024-04-18 13 18 10

**Review by tarakish — COMMENTED** [review]
ご対応ありがとうございます。わかりやすくなりました👍
概ね問題なさそうですが、いくつか表記の面で気になったところがあるので以下ご確認をお願いします！

---

- Bookmark folders
  - `name`カラムがなさそうなのでご確認をお願いします。
- Primary Key
  - railsでは基本的に主キーは`{table_name}_id`ではなく、`id`を用いるため修正いただければと思います。

**Comment by ito-ryo-50a** [comment]
ご確認いただきありがとうございます。
下記、修正いたしました。

・`Bookmark folders`に`name`カラムを追加しました。(記載漏れでした)
・各テーブルの`Primary key`の記述を`id`に修正いたしました。

お手数ですが、ご確認いただけますでしょうか。
よろしくお願いいたします。

[ER図リンク](https://gyazo.com/34fcd616c26280af3a0a560ac0347c7a)

スクリーンショット 2024-04-18 19 57 02

**Review by tarakish — COMMENTED** [review]
修正確認しました。LGTMです！
次の課題に進んでください。

**Comment by ito-ryo-50a** [comment]
ご確認いただきありがとうございます。
引き続き、よろしくお願いいたします。

**Pull request merged**
